### ISSUE TITLE
0.2.0 Exception caught by widgets library 

### ISSUE THREAD

**Issue by Mohammad-Abureesh** [Codelessly/ResponsiveFramework#144]
Sometimes this error is happened , on release the app stop on launch screen because this exception

======== Exception caught by widgets library =======================================================
The following assertion was thrown building MediaQuery(MediaQueryData(size: Size(480.0, -5584.0), devicePixelRatio: 1.8, textScaleFactor: 1.1, platformBrightness: Brightness.dark, padding: EdgeInsets.zero, viewPadding: EdgeInsets(-0.0, -168.0, -0.0, -0.0), viewInsets: EdgeInsets.zero, systemGestureInsets: EdgeInsets(0.0, 24.0, 0.0, 0.0), alwaysUse24HourFormat: false, accessibleNavigation: false, highContrast: false, disableAnimations: false, invertColors: false, boldText: false, navigationMode: traditional, gestureSettings: DeviceGestureSettings(touchSlop: 8.0), displayFeatures: [])):
BoxConstraints has a negative minimum width.

The offending constraints were: BoxConstraints(w=-68.6, 0.0<=h<=Infinity; NOT NORMALIZED)
The relevant error-causing widget was: 
  MediaQuery MediaQuery:file:///C:/Users/LENOVO/AppData/Local/Pub/Cache/hosted/pub.dev/responsive_framework-0.2.0/lib/responsive_wrapper.dart:686:11
When the exception was thrown, this was the stack: 
#0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:520:9)
#1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:551:9)
#2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:578:6)
#3      new RenderConstrainedBox (package:flutter/src/rendering/proxy_box.dart:225:37)
#4      SizedBox.createRenderObject (package:flutter/src/widgets/basic.dart:2426:12)
#5      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5932:52)
#6      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6434:11)
...     Normal element mounting (7 frames)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#14     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#15     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (7 frames)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3702:20)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#27     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
#28     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
#29     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#30     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#31     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#32     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#33     _invoke (dart:ui/hooks.dart:142:13)
#34     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#35     _drawFrame (dart:ui/hooks.dart:112:31)
====================================================================================================

**Comment by mdmm13** [comment]
Might be solved with the a to 1.1.1 via the [migration guide](https://github.com/Codelessly/ResponsiveFramework/issues/151#issuecomment-1714252947?)?
