### ISSUE TITLE
Error when using ReorderableListView inside ResponsiveScaledBox ( v1.1.1 and below)

### ISSUE THREAD

**Issue by kiranvivo** [Codelessly/ResponsiveFramework#163]
Hi, 
Have you Noticed? 
When you try to use the drag feature in the **Flutter ReorderableListView**, it throws 

`
I/flutter (14425):
I/flutter (14425): ===Firebase Crash ERROR Catcher=======
I/flutter (14425):
I/flutter (14425):  , 'package:flutter/src/widgets/scrollable_helpers.dart': Failed assertion: line 238 pos 7: 'globalRect.size.width >= _dragTargetRelatedToScrollOrigin.size.width &&
scrollable_helpers.dart:238
I/flutter (14425):         globalRect.size.height >= _dragTargetRelatedToScrollOrigin.size.height': Drag target size is larger than scrollable size, which may cause bouncing, #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
I/flutter (14425): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
I/flutter (14425): #2      EdgeDraggingAutoScroller._scroll
scrollable_helpers.dart:238
I/flutter (14425): #3      EdgeDraggingAutoScroller.startAutoScrollIfNecessary
scrollable_helpers.dart:223
I/flutter (14425): #4      SliverReorderableListState._dragUpdate.<anonymous closure>
reorderable_list.dart:777
I/flutter (14425): #5      State.setState
framework.dart:1138
I/flutter (14425): #6      SliverReorderableListState._dragUpdate (
I/flutter (14425): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (14425): The following exception was thrown Bug at zoneguard catcher:
I/flutter (14425): 'package:flutter/src/widgets/scrollable_helpers.dart': Failed assertion: line 238 pos 7: 'globalRect.size.width >= _dragTargetRelatedToScrollOrigin.size.width &&
scrollable_helpers.dart:238
I/flutter (14425):         globalRect.size.height >= _dragTargetRelatedToScrollOrigin.size.height': Drag target size is larger than scrollable size, which may cause bouncing
I/flutter (14425): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
I/flutter (14425): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
`[](url)
<img width="1439" alt="Screenshot 2023-11-15 at 11 36 37 PM" src="https://github.com/Codelessly/ResponsiveFramework/assets/17822488/08196254-3a9c-42e6-83e7-7d93b0990267">

**Comment by kiranvivo** [comment]
++
The Card UI animation overflows when held up during drag. It looks like a very critical bug to me.

**Comment by kiranvivo** [comment]
@rayliverified Any thoughts on the above?

**Comment by elkSal** [comment]
Facing same issue with ReorderableListView, when dragging, the item overflows and become bigger than original size.
Quick dirty solution is to use internal padding as follows 
```
ReorderableListView(
                  padding:
                      const EdgeInsets.symmetric(horizontal: 30, vertical: 20),
```

This puts some padding around the list view item so that on drag, it doesn't overflow screen width.

No solution yet?
